name: Build and Push Frontend
on:
  workflow_dispatch:
  push:
    branches:
      - main
  # pull_requests:
  #   types:
  #     - closed

jobs:
  build:
    runs-on: ubuntu-latest
    #if: github.event.pull_request.merged == true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Create lowercased repo owner name
        run: echo "LOWERCASE_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        id: login
        shell: bash
      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Extract tags from last commit
        id: extract_tags
        run: |

To make the workflow more dynamic by setting the push key dynamically, you can use environment variables and expressions in GitHub Actions. You can control the value of the push key based on the presence of tags.

Here’s an updated version of the workflow that sets the push key dynamically:

Example docker-publish.yml
yaml
Copy code
name: Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Convert repository_owner to lowercase
      id: convert_owner
      run: |
        echo "LOWERCASE_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      shell: bash

    - name: Login to GitHub Container Registry using PAT
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Check for Tags
      id: check_tags
      run: |
        tags=$(git tag --contains $(git rev-parse HEAD) | tr '\n' ',' | sed 's/,$//')
        if [ -n "$tags" ]; then
          echo "TAGS_PRESENT=true" >> $GITHUB_ENV
          echo "tags=$(echo $tags | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        else
          echo "TAGS_PRESENT=false" >> $GITHUB_ENV
          echo "tags=latest" >> $GITHUB_ENV
        fi
      - name: Generate SHA from last commit
        id: extract_sha
        run: echo "git_sha=${GITHUB_SHA}" >> $GITHUB_ENV
        shell: bash
      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          push: ${{ env.TAGS_PRESENT == 'true' }}
          build-args: |
            "REACT_APP_API_URL=http://localhost:8080"
            "REPO_URL=${{ github.repository }}"
          tags: |
            ghcr.io/${{ env.LOWERCASE_OWNER }}/flask-app-client:latest
            ghcr.io/${{ env.LOWERCASE_OWNER }}/flask-app-client:${{ env.git_sha }}
            ghcr.io/${{ env.LOWERCASE_OWNER }}/flask-app-client:${{ env.tags }}
          context: .
      - name: Logout from ghcr.io
        run: docker logout ghcr.io


  